-- liquibase formatted sql

-- changeset boris:1
CREATE TABLE IF NOT EXISTS public.users(
    birth_date date,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    login character varying(60) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    pass_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    second_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    third_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_login_key UNIQUE (login),
    CONSTRAINT users_role_check CHECK (role::text = ANY (ARRAY['USER'::character varying, 'ADMIN'::character varying]::text[]))
);
CREATE TABLE IF NOT EXISTS public.cards
(
    balance numeric(12,2) NOT NULL,
    expiry_date date NOT NULL,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    last_four_digits character varying(4) COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    bank_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    card_number character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cards_pkey PRIMARY KEY (id),
    CONSTRAINT cards_card_number_key UNIQUE (card_number),
    CONSTRAINT fkcmanafgwbibfijy2o5isfk3d5 FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT cards_status_check CHECK (status::text = ANY (ARRAY['ACTIVE'::character varying, 'BLOCK'::character varying, 'EXPIRED'::character varying]::text[]))
);
CREATE TABLE IF NOT EXISTS public.blockings
(
    card_id integer NOT NULL,
    date_time timestamp(6) without time zone,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT blockings_pkey PRIMARY KEY (id),
    CONSTRAINT fkj0s5mu59qbvogtgg5jqvmw1sp FOREIGN KEY (card_id)
        REFERENCES public.cards (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT blockings_status_check CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'CANCELLED'::character varying, 'CONFIRM'::character varying]::text[]))
);
CREATE TABLE IF NOT EXISTS public.transfers
(
    amount numeric(12,2) NOT NULL,
    card_from_id integer NOT NULL,
    card_to_id integer NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT transfers_pkey PRIMARY KEY (id),
    CONSTRAINT fk6jyor2k12relmgr5usdgs1d4a FOREIGN KEY (card_from_id)
        REFERENCES public.cards (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fkfq5w6nri9fgeirldmr2yy8nkp FOREIGN KEY (card_to_id)
        REFERENCES public.cards (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);