spring:
  application:
    name: bankcards

  # ===================================================================
  # НАСТРОЙКИ БАЗЫ ДАННЫХ
  # ===================================================================
  datasource:
    url: jdbc:postgresql://localhost:5433/Bank
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

    # Настройки пула соединений Hikari
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # Стратегии именования
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


    # Показывать SQL запросы
    show-sql: true

    # Форматировать SQL
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

card:
  encryption:
    # Секретный ключ (в реальном проекте - через переменные окружения!)
    secret: 3lwefsa0
    # Алгоритм шифрования
    algorithm: AES
    # Режим шифрования (для простоты используем ECB, в продакшене лучше GCM)
    transformation: AES/ECB/PKCS5Padding

# ===================================================================
# ОСНОВНЫЕ НАСТРОЙКИ ПРИЛОЖЕНИЯ
# ===================================================================
server:
  port: 8080